# Generated by Django 4.2.11 on 2024-04-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBVpractice', '0002_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=99, null=True, verbose_name='价格'),
        ),
    ]
